REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:NormalCategoryChanceNormal', 1600);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ChampionCategoryChanceNormal', 250);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:RareCategoryChanceNormal', 10);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:UniqueCategoryChanceNormal', 4);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:SuperUniqueCategoryChanceNormal', 2);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:BossCategoryChanceNormal', 1);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:NormalCategoryChanceNightmare', 1000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ChampionCategoryChanceNightmare', 250);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:RareCategoryChanceNightmare', 20);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:UniqueCategoryChanceNightmare', 8);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:SuperUniqueCategoryChanceNightmare', 4);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:BossCategoryChanceNightmare', 2);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:NormalCategoryChanceHell', 750);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ChampionCategoryChanceHell', 250);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:RareCategoryChanceHell', 40);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:UniqueCategoryChanceHell', 16);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:SuperUniqueCategoryChanceHell', 8);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:BossCategoryChanceHell', 3);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop0ChanceNormal', 200);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop1ChanceNormal', 1000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop2ChanceNormal', 400);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop3ChanceNormal', 200);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop4ChanceNormal', 100);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop5ChanceNormal', 50);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop6ChanceNormal', 25);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop0ChanceNightmare', 5000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop1ChanceNightmare', 1000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop2ChanceNightmare', 400);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop3ChanceNightmare', 300);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop4ChanceNightmare', 200);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop5ChanceNightmare', 50);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop6ChanceNightmare', 25);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop0ChanceHell', 4000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop1ChanceHell', 1000);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop2ChanceHell', 400);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop3ChanceHell', 350);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop4ChanceHell', 250);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop5ChanceHell', 80);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'NPC:ItemDrop6ChanceHell', 40);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:StartZoneID', 4);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:StartZoneX', 199.48);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:StartZoneY', 5055);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:StartZoneZ', -4.36);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:StartZoneHeading', 255.5);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'World:EnableTutorialButton', 'false');
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:FoodLoss', 'false');
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Combat:FleeHPRatio', 0);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:LeaveCorpses', 0);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:LeaveNakedCorpses', 0);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:DeathItemLossLevel', 255);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:HealOnLevel', true);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:UnmemSpellsOnDeath', false);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:RestRegenPercent', 20);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Zone:PEQZoneReuseTime', 0);
REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(1, 'Character:MaxFearDurationForPlayerCharacter', 1);
UPDATE zone SET min_status = 250 WHERE EXPANSION > 3;
ALTER TABLE `eqemu`.`items` CHANGE COLUMN `augslot1visible` `augslot1visible` TINYINT(3) NULL DEFAULT 0 , CHANGE COLUMN `augslot2visible` `augslot2visible` TINYINT(3) NULL DEFAULT 0 , CHANGE COLUMN `augslot3visible` `augslot3visible` TINYINT(3) NULL DEFAULT 0 , CHANGE COLUMN `augslot4visible` `augslot4visible` TINYINT(3) NULL DEFAULT 0 , CHANGE COLUMN `augslot5visible` `augslot5visible` TINYINT(3) NULL DEFAULT 0 ;
DELETE FROM starting_items WHERE id > 0;
UPDATE zone SET rain_chance1=0, rain_chance2=0, rain_chance3=0, rain_chance4=0, rain_duration1=0, rain_duration2=0, rain_duration3=0, rain_duration4=0, rain_duration1=0, snow_chance1=0, snow_chance2=0, snow_chance3=0, snow_chance4=0, snow_duration1=0, snow_duration2=0, snow_duration3=0, snow_duration4=0, snow_duration1=0;
REPLACE INTO `items` (`id`, `minstatus`, `Name`, `aagi`, `ac`, `accuracy`, `acha`, `adex`, `aint`, `artifactflag`, `asta`, `astr`, `attack`, `augrestrict`, `augslot1type`, `augslot1visible`, `augslot2type`, `augslot2visible`, `augslot3type`, `augslot3visible`, `augslot4type`, `augslot4visible`, `augslot5type`, `augslot5visible`, `augslot6type`, `augslot6visible`, `augtype`, `avoidance`, `awis`, `bagsize`, `bagslots`, `bagtype`, `bagwr`, `banedmgamt`, `banedmgraceamt`, `banedmgbody`, `banedmgrace`, `bardtype`, `bardvalue`, `book`, `casttime`, `casttime_`, `charmfile`, `charmfileid`, `classes`, `color`, `combateffects`, `extradmgskill`, `extradmgamt`, `price`, `cr`, `damage`, `damageshield`, `deity`, `delay`, `augdistiller`, `dotshielding`, `dr`, `clicktype`, `clicklevel2`, `elemdmgtype`, `elemdmgamt`, `endur`, `factionamt1`, `factionamt2`, `factionamt3`, `factionamt4`, `factionmod1`, `factionmod2`, `factionmod3`, `factionmod4`, `filename`, `focuseffect`, `fr`, `fvnodrop`, `haste`, `clicklevel`, `hp`, `regen`, `icon`, `idfile`, `itemclass`, `itemtype`, `ldonprice`, `ldontheme`, `ldonsold`, `light`, `lore`, `loregroup`, `magic`, `mana`, `manaregen`, `enduranceregen`, `material`, `herosforgemodel`, `maxcharges`, `mr`, `nodrop`, `norent`, `pendingloreflag`, `pr`, `procrate`, `races`, `range`, `reclevel`, `recskill`, `reqlevel`, `sellrate`, `shielding`, `size`, `skillmodtype`, `skillmodvalue`, `slots`, `clickeffect`, `spellshield`, `strikethrough`, `stunresist`, `summonedflag`, `tradeskills`, `favor`, `weight`, `UNK012`, `UNK013`, `benefitflag`, `UNK054`, `UNK059`, `booktype`, `recastdelay`, `recasttype`, `guildfavor`, `UNK123`, `UNK124`, `attuneable`, `nopet`, `updated`, `comment`, `UNK127`, `pointtype`, `potionbelt`, `potionbeltslots`, `stacksize`, `notransfer`, `stackable`, `UNK134`, `UNK137`, `proceffect`, `proctype`, `proclevel2`, `proclevel`, `UNK142`, `worneffect`, `worntype`, `wornlevel2`, `wornlevel`, `UNK147`, `focustype`, `focuslevel2`, `focuslevel`, `UNK152`, `scrolleffect`, `scrolltype`, `scrolllevel2`, `scrolllevel`, `UNK157`, `serialized`, `verified`, `serialization`, `source`, `UNK033`, `lorefile`, `UNK014`, `svcorruption`, `skillmodmax`, `UNK060`, `augslot1unk2`, `augslot2unk2`, `augslot3unk2`, `augslot4unk2`, `augslot5unk2`, `augslot6unk2`, `UNK120`, `UNK121`, `questitemflag`, `UNK132`, `clickunk5`, `clickunk6`, `clickunk7`, `procunk1`, `procunk2`, `procunk3`, `procunk4`, `procunk6`, `procunk7`, `wornunk1`, `wornunk2`, `wornunk3`, `wornunk4`, `wornunk5`, `wornunk6`, `wornunk7`, `focusunk1`, `focusunk2`, `focusunk3`, `focusunk4`, `focusunk5`, `focusunk6`, `focusunk7`, `scrollunk1`, `scrollunk2`, `scrollunk3`, `scrollunk4`, `scrollunk5`, `scrollunk6`, `scrollunk7`, `UNK193`, `purity`, `evoitem`, `evoid`, `evolvinglevel`, `evomax`, `clickname`, `procname`, `wornname`, `focusname`, `scrollname`, `dsmitigation`, `heroic_str`, `heroic_int`, `heroic_wis`, `heroic_agi`, `heroic_dex`, `heroic_sta`, `heroic_cha`, `heroic_pr`, `heroic_dr`, `heroic_fr`, `heroic_cr`, `heroic_mr`, `heroic_svcorrup`, `healamt`, `spelldmg`, `clairvoyance`, `backstabdmg`, `created`, `elitematerial`, `ldonsellbackrate`, `scriptfileid`, `expendablearrow`, `powersourcecapacity`, `bardeffect`, `bardeffecttype`, `bardlevel2`, `bardlevel`, `bardunk1`, `bardunk2`, `bardunk3`, `bardunk4`, `bardunk5`, `bardname`, `bardunk7`, `UNK214`, `UNK219`, `UNK220`, `UNK221`, `heirloom`, `UNK223`, `UNK224`, `UNK225`, `UNK226`, `UNK227`, `UNK228`, `UNK229`, `UNK230`, `UNK231`, `UNK232`, `UNK233`, `UNK234`, `placeable`, `UNK236`, `UNK237`, `UNK238`, `UNK239`, `UNK240`, `UNK241`, `epicitem`) VALUES ('100005', '0', 'Arrow', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '285', '4278190080', '0', '0', '0', '8', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '0', '598', 'IT10', '0', '27', '0', '0', '0', '0', 'Arrow', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '65535', '25', '0', '0', '0', '1', '0', '1', '-1', '0', '2097152', '-1', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2015-12-05 09:40:08', '', '0', '0', '0', '0', '100', '0', '1', '', '0', '-1', '0', '0', '0', '0', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '0', '0', '0', NULL, '2016-03-01 21:00:37', NULL, '13THFLOOR', '0', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '1', '00000000000000000000', '0', '', '-1', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '0', '', '', '', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2015-11-28 18:07:22', '0', '70', '0', '0', '0', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '-256', '255', '0', '0', '0', '0', '0', '0', '0', '0');
DELETE FROM merchantlist where item < 8100;